config/routes.rb
Rails.application.routes.draw do
  get 'pages/create'
  get 'pages/index'
  get 'pages/board'
  # resources :pages
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project_m.rb
class ProjectM < ApplicationRecord
   validates :name, presence: true
   validates :description, presence true
   validates :status, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index 
    
  end
  
  
  def create
    @task = Task.create(name: params[:name], description: params[:description], start_date: params[:start_date], finish_date: params[:finish_date], status: params[:status])
  end

  

  def board
    if params[:status].present?
      @tasks = Task.where('state = ?'), params[:state]
    else
      @tasks = Task.all
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  </head>

  <body>
    
      
      
      
      
      
     <%= yield %>
    
   
  </body>

  <footer>
    <!-- script bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

  </footer>

</html>

app/views/pages/board.html.erb
<h2>Listado de tareas</h2>

<div class ="container">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripción</th>
                <th scope="col">Detalle</th>
                <th scope="col">Inicio</th>
                <th scope="col">Término</th>
                <th scope="col">Estado</th>
            </tr>
        </thead>
        <tbody>
            <% @task.each do |task| %>
                <tr>
                    <th scope="row"><%= task.id %></th>
                    <td><%= task.name %></td>
                    <td><%= task.description %></td> 
                    <td><%= task.start_date %></td> 
                    <td><%= task.finish_date %></td>
                    <td><%= task.status %></td>
                    <td>
                        <% if task.status == 1%>
                            Propuesta
                        <% elsif task.status == 2%>
                            En Progreso
                        <% else %>
                            Terminado
                        <% end %>
                    </td>
                </tr>
            <% end %> 
        </tbody>
    </table>
</div>

app/views/pages/create.html.erb
 
 <% if @task.success.any?
    <div> 
        <h2>¿Tarea Creada!</h1>
        <p>Ha iniciado una nueva tarea</p>
        <p>Para acceder a sus actividades click aquí <%= link_to "board", pages_board_path %></p>
        
    </div>
<%= else %>
    

app/views/pages/index.html.erb
{
    <h2>Crear Tarea</h2>
<form method="get" action="pages/create" class ="container">
    <div class="container">
        <div class ="col" class="mb-3">
            <label for="name" class="form-label">Nombre Tarea</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="form-group" class ="mb-3">
            <label for="exampleFormControlTextarea1">Descripcion</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"></textarea>
        </div>
        <div class = "row" class="mb-3">
            <div>
                <label for="name" class="form-label">Fecha Inicio</label>
                <input type="date" class="form-control" name="start_date">
            </div>
            &nbsp;
            <div>
                <label for="name" class="form-label">Fecha Término</label>
                <input type="date" class="form-control" name="finish_date">
            </div>
            &nbsp;
            <div class ="form-select" class="mb-3">
                <label for="name" class="form-label">Estado</label>
                <select class="custom-select" class = container>
                    <option selected value ="1">Propuesta</option>
                    <option value="2">En Progreso</option>
                    <option value="3">Terminada</option>
                </select>
            </div>
        </div>   
        <br>            
        <input class="btn btn-primary" class = mb-3 type="submit" value="Crear">
           
    </div>
</form>